### PR TITLE
Add filter by country

### PR DESCRIPTION
**Pull request by hanbyul-here**
Add filter by country on supply chain page using react select's multi select functionality. : https://deploy-preview-43--objective-tereshkova-f5972d.netlify.app/supply-chain

I also added options to choose a country to the selector on the navigation. When a country is selected, it will take the user to the total emission page with the matching filter. (total emission page doesn't have country filter yet, so the page gets directed to the total emission page without any filter applied for now. will work on it after https://github.com/RMI-Climate-Intelligence/oci/pull/40 is merged.)

### CODE REVIEW

**Review by danielfdsilva — CHANGES_REQUESTED** [review]
When you select a country through the Dropdown you end up on the Total Emissions page with a filter by country, but it is not possible to remove it once set.

The Total Emissions page should probably have the country filter like the "Supply Chain"

**Comment by hanbyul-here** [comment]
@danielfdsilva Yeah, I meant to put interactive country filter on total emission page as a follow up since it will be better to see it working with new tree map page. I thought it is ok to separate functions in this way since `v2` is not a production branch yet? but if you think this half-baked functionality shouldn't go into v2, I can comment out the code shows the country option in the dropdown for now.

**Comment by danielfdsilva** [comment]
@hanbyul-here If you feel the treemap is done, we can merge that one first, then merge it into this and finish the feature

**Comment by hanbyul-here** [comment]
@danielfdsilva yeah let's do that

**Comment by hanbyul-here** [comment]
- I squeezed a small change in nav (there were two 'Maps' on nav)
- I also noticed that total emission page doesn't handle the case when there is no oil matching to filter, so added a simple text warning about it.

**Review by danielfdsilva — APPROVED** [review]
Fantastic! :shipit:

**Pull request merged**
