### PR TITLE
Implement treemap for total emissions page

### PR DESCRIPTION
**Pull request by danielfdsilva**
This PR adds the treemap visualization to the total emissions page.
The resources as displayed in groups according to their type and colored accordingly. The size of each area is tied to the `productionVolume` of the oils. _This is easy to change if needed._

The root view shows a small popup to view the full label, which is useful when it is truncated.
image

When an area gets selected we get a breakdown of the resources in that group and an informative tooltip.
image

The sidebar filters are connected to the visualization and it will update when one is selected.

@hanbyul-here the filters to keep/remove must probably be reviewed. I tried to document the code with comments. If something is not very clear let me know.

### CODE REVIEW

**Comment by hanbyul-here** [comment]
Leaving some unexpected behaviors that I found while reviewing the code: 

If I interact with filters before treemap animation is done, empty spaces appear in treemap like below.
to reproduce: quickly select multiple regions before animation is done.

Screen Shot 2021-11-22 at 1 19 00 PM
Screen Shot 2021-11-22 at 1 18 39 PM


The shadows sometimes don't sync like below. 
to reproduce: select dry gas, then select Middle East & North Africa. 
Screen Shot 2021-11-22 at 1 31 58 PM

**Comment by danielfdsilva** [comment]
@hanbyul-here I refactored the root treemap and I think this fixes all the kinks.

**Comment by hanbyul-here** [comment]
Beautiful, thanks!

+  nitpick:  I wonder it would be better to hide detail tooltip when selectedtype is null (when root treemap is supposed to be displayed). Since there is transition time, I sometimes get double tooltips if I quickly move my cursor from metabar to the detailed block after clicking. (trying to attach the screenshot, but github is acting out I will try again later.)

+ I agree that we needed d3 to handle dom manipulation for this treemap It would be good to document why we used different approaches for d3+ react in the same repo.

**Review by hanbyul-here — APPROVED** [review]

**Comment by danielfdsilva** [comment]
@hanbyul-here I was not able to replicate the double tooltips in any way. I did merge `v2` into this branch to solve the conflicts. Let me know if the error is still happening for you.

**Comment by hanbyul-here** [comment]
Yeah, error still happens but honestly I kind of have to try hard to reproduce. so I think it is good to go!

**Pull request merged**
